### ISSUE TITLE
Por que o DDD de todos os telefones é 61?

### ISSUE THREAD

**Issue by thiagogsr** [EdDeAlmeidaJr/politicosbr#14]

**Comment by eduBKR** [comment]
Por que esse número é do gabinete em brasília :D

**Comment by thiagogsr** [comment]
Entendi

**Comment by EdDeAlmeidaJr** [comment]
Obrigado @eduBKR. Exatamente @thiagogsr, todos os telefones são de Brasília. Não tenho ainda os telefones nas bases de cada um, mas estou pesquisando. Se alguém souber uma fonte, agradeço.
